# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_nnlm <- function(x, y, alpha, mask, beta0, max_iter, rel_tol, n_threads, method) {
    .Call(`_NNLM_c_nnlm`, x, y, alpha, mask, beta0, max_iter, rel_tol, n_threads, method)
}

c_nnmf <- function(A, k, W, H, Wm, Hm, alpha, beta, max_iter, rel_tol, n_threads, verbose, show_warning, inner_max_iter, inner_rel_tol, method, trace) {
    .Call(`_NNLM_c_nnmf`, A, k, W, H, Wm, Hm, alpha, beta, max_iter, rel_tol, n_threads, verbose, show_warning, inner_max_iter, inner_rel_tol, method, trace)
}

